# Patch for changing kourier to a NodePort for installations where a 
# LoadBalancer is not available (for example local Kind clusters)
spec:
  ports:
  - name: http2
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 8443
  type: NodePort
