# CloudFlare API key
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: cert-manager
type: Opaque
data:
  # Create token in CloudFlare UI, giving it zone read and dns write
  # permissions.  Create the value for the token using:
  #   echo -n 'raw-token-here' | base64
  token: "Q3VfaHNrbVRRN0x0RU9VVlpGNTlqLXc1eWZuR05neFJyZkFCaWJvYw=="
