---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod
  region: us-west-2
  version: '1.15'

nodeGroups:
  - name: workers
    labels:
      group: workers
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 50
    ssh:
      publicKeyPath: keys/ssh.pub
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

