name: Func E2E Test

on: [pull_request]

jobs:
  test:
    name: E2E Test for Runtimes
    strategy:
      matrix:
        go: [1.16.x]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Local Registry
        run: ./hack/registry.sh
      - name: Build
        run: make
      - name: E2E
        run: make test-e2e
      - name: E2E go
        run: make test-e2e-runtime runtime=go
      - name: E2E python
        run: make test-e2e-runtime runtime=python
      - name: E2E quarkus
        run: make test-e2e-runtime runtime=quarkus
      - name: E2E springboot
        run: make test-e2e-runtime runtime=springboot
      - name: E2E typescript
        run: make test-e2e-runtime runtime=typescript
